name: create_mirror_gitsvn
on:
  push:
  workflow_dispatch:

jobs:
  create_mirror_gitsvn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          key: ttssh2-cache
          path: ttssh2
      - name: install
        shell: bash
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get remove -y git git-man
          sudo apt-get install -y git git-svn
      - name: git svn
        shell: bash
        run: |
          bash convert.sh
        env:
          GIT_REPOSITORY: ${{ secrets.GIT_REPOSITORY }}
          GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}
      - name: git_svn_tar
        uses: actions/upload-artifact@v2
        with:
          name: git_svn_tar
          path: ./ttssh2_git.tar.bz2
          retention-days: 3
